project:
  type: website

website:
  title: "15th SEHM"
  favicon: assets/favicon.ico
  navbar:
    left:
      - href: index.qmd
        icon: house
        text: Home
      - href: programme.qmd
        icon: calendar
        text: Programme
      - href: venues.qmd
        icon: school
        text: Venues
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

