project:
  type: website
  output-dir: docs

website:
  favicon: assets/favicon.ico
  navbar:
    left:
      - href: index.qmd
        icon: house
        text: Home
      - text: "{{< fa signs-post >}} Registration"
        menu:
          # - href: registration.qmd
            # text: "{{< fa user >}} Register"
          - href: propose.qmd
            text: "{{< fa comment >}} Propose a session"
          # - href: paper-submit.qmd
            # text: "{{< fa newspaper >}} Submit an abstract"
    right:
      - text: "{{< fa train >}} Travel"
        href: logistics/travel.qmd
      - text: "{{< fa hotel >}} Accomodation"
        href: logistics/accomodation.qmd
      - text: "More"
        icon: flower1
        menu:
          - href: info.qmd
            text: "News"
          - href: info.qmd
            text: "Information"
          - href: info.qmd
            text: "FAQs"

format:
  html:
    theme:
    - flatly
    - custom.scss
    css: styles.css
    toc: true

execute:
  echo: false
  warning: false
  message: false
