project:
  type: website
  output-dir: docs

website:
  title: "15th SEHM"
  favicon: assets/favicon.ico
  navbar:
    left:
      - href: index.qmd
        icon: house
        text: Home
      - href: programme.qmd
        icon: calendar
        text: Programme
      - href: venues.qmd
        icon: building
        text: Venues
    right:
      - text: "Logistics"
        menu:
          - text: "Travel"
            icon: house-heart
            href: logistics/travel.qmd
          - text: "Accomodation"
            icon: house-heart
            href: logistics/accomodation.qmd
      - href: planning.qmd
        icon: flower1
        text: Planning

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  echo: false
  warning: false
  message: false
