project:
  type: website
  output-dir: docs

website:
  title: "SEHM {{< fa person-chalkboard >}}"
  favicon: assets/favicon.ico
  navbar:
    left:
      - href: index.qmd
        icon: house
        text: Home
      - href: programme.qmd
        icon: calendar
        text: Programme
      - href: venues.qmd
        icon: building
        text: Venues
    right:
      - text: "Logistics"
        menu:
          - text: "{{< fa train >}} Travel"
            href: logistics/travel.qmd
          - text: "{{< fa hotel >}} Accomodation"
            href: logistics/accomodation.qmd
      - href: planning.qmd
        icon: flower1
        text: Planning

format:
  html:
    theme:
    - flatly
    - custom.scss
    css: styles.css
    toc: true

execute:
  echo: false
  warning: false
  message: false
