---
title: "News"
---

We are pleased to announce that the meeting will actually take place in Lund.

The registration for the conference is now open. It closes on October 1.  

### Registration dates

Registration is open until

### What is the scope for digital attendance?

A few of the venues have nice cameras...

We have received many questions about online participation. This conference cannot be a so-called hybrid conference. The reason is that the lecture halls do not offer the necessary equipment allowing interactions between online participants and those in the lecture halls.

Those who are in Lund but wish to participate in a panel that is a zoom meeting do so through their own laptops. There is no registration fee attached to online (only) participation. But for the record we urge all participants, whether going to Lund or organizing only a zoom meeting, to register for the conference. In the registration form, choose “I will attend online only”. Please remember to book your accommodation

### Registration form

You can access the registration form [here](registration.qmd)
